# -*- coding: utf-8 -*-
"""천영성 - 첫 번째 과제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TgKCRDLJ_7dinC35RF2UvafDupbXIYvR

## **00 과제 제출 예시**
아래와 같이 출력 결과와 동일한 출력을 해주시면 됩니다.
"""

# 출력 결과 : 광주 인공지능사관학교
print("광주 인공지능사관학교")

"""## **01 "Hello World!" 출력하기**
Hello World!를 출력해 주세요.
"""

# 출력 결과 : Hello World!
print('Hello World!')

"""## **02 데이터 타입**
다음 변수 a, 변수 b, 변수 c의 자료형을 한 줄에 출력해 주세요.
"""

# 주어진 변수(a, b, c) 직접 수정 불가
# 출력 결과 (<class 'str'> <class 'int'> <class 'bool'>)

a = 'str'
b = 123
c = True
print(type(a),type(b),type(c))

"""## **03 사칙연산**
아래 1), 2), 3), 4)를 보시고 한 줄에 출력해 주세요. 

1) a의 b 제곱을 출력하시오.

2) a를 b로 나눈 나머지를 출력하시오.

3) a를 b로 나눈 몫을 출력하시오.

4) a를 b로 나눈 값을 출력하시오.
"""

# 주어진 변수 (a, b) 직접 수정 불가
# 출력 결과 (2401 3 1 1.75)

a = 7
b = 4
print(a**b,a%b,a//b,a/b)

"""## **04 평균 구하기**
광주 인공지능사관학교를 다니는 홍길동 씨의 1주차 과목별 점수는 다음과 같다. 주어진 변수를 활용하여 홍길동 씨의 평균 점수를 출력해 주세요.

- 인공지능을 위한 수학 : 78
- 머신러닝 : 83
- 딥러닝 : 89
- 알고리즘 : 76
"""

# 주어진 변수(ai_math, machine_learning, deep_learning, algorithm) 직접 수정 불가
# 출력 결과 (81.75)
ai_math = 79
machine_learning = 83
deep_learning = 89
algorithm = 76

print((ai_math+machine_learning+deep_learning+algorithm)/4)

"""## **05 문자열 인덱싱과 슬라이싱**
'Gwang ju'의 'j'와 'ang j'를 인덱싱을 활용하여 한 줄에 출력해 주세요.


"""

# 주어진 변수 (str_ai) 직접 수정 불가
# 출력 결과 (j ang j)
str_ai = 'Gwang ju'
print(str_ai[6],str_ai[2:7])

"""## **06 리스트 인덱싱**
아래 list_ai 안의 ['a', 'b', 'c']를 인덱싱을 활용하여 출력해 주세요.
"""

# 주어진 변수(list_ai) 직접 수정 불가
# 출력 결과 (['a', 'b', 'c'])

list_ai = [1, 2, 3, ['a', 'b', 'c']]
print(list_ai[3])

"""## **07 삼중 리스트 인덱싱**
아래 list_ai 안의 문자 'A'와 'I'를 인덱싱과 문자열 더하기를 활용하여 'AI'로 출력해 주세요.
"""

# 주어진 변수 (list_ai) 직접 수정 불가
# 출력 결과 ('AI')
list_ai = ['C', 'School', ['A', 'Gwang', ['Ju', 'I']]]

print(list_ai[2][0]+list_ai[2][2][1])

"""## **08 리스트 뒤집기**
아래 list_ai을 내장함수를 사용하여 거꾸로 출력해 주세요.
"""

# 주어진 변수(list_ai) 직접 수정 불가
# 출력 결과 (['광', '주', '인', '공', '지', '능', '사', '관', '학', '교'])

list_ai = ['교', '학', '관', '사', '능', '지', '공', '인', '주', '광']

print(list_ai[::-1])

"""## **09 문자열 나누기**
아래의 str_ai, str_ai2 변수를 내장함수를 활용하여 ['광주', '인공지능', '사관학교']가 2번 나오도록 출력해 주세요.
"""

# 주어진 변수(str_ai, str_ai2) 및 print(str_ai, str_ai2)문 직접 수정 불가
# 출력 결과 (['광주', '인공지능', '사관학교'] ['광주', '인공지능', '사관학교'])

str_ai = '광주 인공지능 사관학교'
str_ai2 = '광주;인공지능;사관학교'



print(str_ai.split(),str_ai2.split(';'))

"""## **10 문자열 바꾸기**
아래의 str_ai 변수에 할당된 '괌주 인공지능사관학교' 문자열에서 오타인 '괌주'를 내장함수를 활용하여 '광주'로 바꾸어 '광주 인공지능사관학교'로 출력해 주세요.
"""

# 주어진 변수 (str_ai) 및 print(str_ai)문 직접 수정 불가
# 출력 결과 (광주 인공지능사관학교)

str_ai = '괌주 인공지능사관학교'


print(str_ai.replace('괌','광'))

"""## **11 리스트 정렬**
광주 인공지능사관학교 학생인 홍길동은 이번 시험 성적이 담긴 리스트 scores를 높은 성적순으로 정렬을 하려고 한다. 내장함수를 활용하여 리스트를 재정렬 후 출력해 주세요.
"""

# 주어진 변수(scores) 및 print(scores) 직접 수정 불가
# 출력 결과 : [89, 83, 78, 76]

scores = [78, 83, 89, 76]


scores.sort(reverse=True)
print(scores)

"""## **12 리스트 요소 추가**
아래 리스트list_ai의 마지막 요소로 int_ai를 추가하려고 한다. 내장함수를 활용하여 int_ai가 포함된 list_ai를 출력해 주세요.
"""

# 주어진 변수(list_ai, int_ai) 및 print(list_ai) 직접 수정 불가
# 출력 결과 : [78, 77, 54, 55, 87, 98]

list_ai = [78,77,54,55,87]
int_ai = 98


list_ai.append(int_ai)
print(list_ai)

"""## **13 리스트 총 개수(길이)**
아래의 list_ai의 요소 총개수(길이)를 내장함수를 사용하여 출력해 주세요.
"""

# 주어진 변수(list_ai) 직접 수정 불가
# 출력 결과 : 5

list_ai = ['인공', '광주', '사관', '학교', '지능']
print(len(list_ai))

"""## **14 리스트 요소 위치 반환**
아래의 list_ai의 요소 중 '학교'의 위치를 내장함수를 사용하여 출력해 주세요.
"""

# 주어진 변수(list_ai) 직접 수정 불가
# 출력 결과 : 3

list_ai = ['인공', '광주', '사관', '학교', '지능']
print(list_ai.index('학교'))